main:
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 1
  - identifier: series
    name: Series
    url: /series/
    weight: 2
  - identifier: start
    name: Start
    url: /start/
    weight: 3
  - identifier: about
    name: About
    url: /about/
    weight: 4
  - identifier: subscribe
    name: Subscribe
    url: /newsletter/
    weight: 5
