main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 2
  - identifier: archives
    name: Archive
    url: /archives/
    weight: 3
  - identifier: series
    name: Series
    url: /series/
    weight: 4
  - identifier: about
    name: About
    url: /about/
    weight: 5
  - identifier: subscribe
    name: Subscribe
    url: https://jamalhansen.beehiiv.com
    weight: 6
  - identifier: search
    name: Search
    url: /search/
    weight: 7
