[project]
name = "jamalhansen-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cookiecutter>=2.6.0",
    "render-engine>=2024.11.1",
    "rich>=14.0.0",
    "typer>=0.15.2",
    "watchfiles>=1.0.5",
]
